name: CI Pipeline

on:
  push:
    branches:
      - master  # Pipeline będzie uruchamiany dla pushy na gałęzi main
  pull_request: # Pipeline będzie również uruchamiany dla PR
    branches:
      - master

jobs:
  lint-and-test:
    name: Super-Linter and Unit Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Uruchom Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true # Waliduj cały kod
          DEFAULT_BRANCH: master        # Główna gałąź
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Setup środowiska dla testów (przykład z Pythonem)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 4. Zainstaluj zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Plik z zależnościami (dostosuj do swojego projektu)

      # 5. Uruchom testy jednostkowe
      - name: Run unit tests
        run: |
          pytest tests/  # Uruchamia testy w katalogu `tests`